"""pytest configuration — network is blocked, fixtures are optional.

NO TEST IN THIS SUITE MAY SPEND VENDOR MONEY. The only live call permitted anywhere in the
skill's test surface is a zero-cost auth probe (BatchData `POST {}` -> 400 live / 401 dead;
Sherpa `PUT /api/person {}` -> 403 dead; Melissa rejected keys cost $0), and only behind
`--probe`. So this blocks the socket layer outright for the whole session.
"""

from __future__ import annotations

import pathlib
import socket
import sys

import pytest

SKILL_DIR = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_DIR / "scripts"))

import octlib  # noqa: E402


@pytest.fixture(autouse=True, scope="session")
def _block_network():
    """Any accidental network call raises rather than quietly spending money."""
    def _blocked(*a, **k):
        raise RuntimeError(
            "network blocked in tests. No eval may spend vendor money; the only live call "
            "permitted in this skill's test surface is a zero-cost auth probe behind "
            "--probe.")

    real_socket, real_create = socket.socket, socket.create_connection
    socket.socket = _blocked
    socket.create_connection = _blocked
    try:
        yield
    finally:
        socket.socket, socket.create_connection = real_socket, real_create


@pytest.fixture(scope="session")
def skill_dir():
    return SKILL_DIR


@pytest.fixture(scope="session")
def fixtures_dir():
    """<cache_root>/fixtures, or skip.

    Fixture PII stays out of the repo. Payloads are generated by tests/make_fixtures.py into
    the cache; tests skip rather than fail when it has not been run.
    """
    d = octlib.cache_root() / "fixtures"
    if not d.is_dir():
        pytest.skip("fixtures absent — run tests/make_fixtures.py")
    return d


@pytest.fixture(scope="session")
def real_fixtures_dir():
    """<cache_root>/fixtures/real — operator-supplied recorded payloads.

    When present these are the TRUE controls (real digits, real people) and must never enter
    the repo. When absent the synthetic equivalents carry the same structure and every
    assertion still holds, because the assertions are about status and shape.
    """
    d = octlib.cache_root() / "fixtures" / "real"
    if not d.is_dir():
        pytest.skip("real recorded payloads absent — synthetic equivalents are used instead")
    return d
